"""Add onboarding model

Revision ID: 3a6545303a8e
Revises: a587b323299a
Create Date: 2026-01-05 19:28:41.692123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6545303a8e'
down_revision = 'a587b323299a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_responses',
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('content_hours_per_week', sa.String(length=50), nullable=True),
    sa.Column('performs_live', sa.String(length=50), nullable=True),
    sa.Column('preferred_content_types', sa.JSON(), nullable=True),
    sa.Column('inspiring_artists', sa.Text(), nullable=True),
    sa.Column('genre_fallback', sa.String(length=100), nullable=True),
    sa.Column('visual_styles', sa.JSON(), nullable=True),
    sa.Column('visual_style_followup', sa.JSON(), nullable=True),
    sa.Column('top_challenges', sa.JSON(), nullable=True),
    sa.Column('whats_working', sa.JSON(), nullable=True),
    sa.Column('upcoming_music', sa.String(length=50), nullable=True),
    sa.Column('release_timeline', sa.String(length=50), nullable=True),
    sa.Column('specific_release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collaboration_plans', sa.String(length=50), nullable=True),
    sa.Column('current_question', sa.String(length=50), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_onboarding_responses_artist_id'), 'onboarding_responses', ['artist_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_responses_artist_id'), table_name='onboarding_responses')
    op.drop_table('onboarding_responses')
    # ### end Alembic commands ###

