"""Initial schema

Revision ID: a587b323299a
Revises: 
Create Date: 2026-01-05 17:24:57.103707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = 'a587b323299a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('artists',
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_index(op.f('ix_artists_user_id'), 'artists', ['user_id'], unique=False)
    op.create_table('content_posts',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index('idx_content_posts_artist', 'content_posts', ['artist_id', 'posted_at'], unique=False)
    op.create_index(op.f('ix_content_posts_artist_id'), 'content_posts', ['artist_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('metric_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('artist_id', 'date', 'platform', 'metric_name', name='uq_daily_metrics')
    )
    op.create_index('idx_daily_metrics_artist_date', 'daily_metrics', ['artist_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_metrics_artist_id'), 'daily_metrics', ['artist_id'], unique=False)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index(op.f('ix_experiments_artist_id'), 'experiments', ['artist_id'], unique=False)
    op.create_table('platform_connections',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_index('idx_platform_connections_artist_platform', 'platform_connections', ['artist_id', 'platform'], unique=True)
    op.create_index(op.f('ix_platform_connections_artist_id'), 'platform_connections', ['artist_id'], unique=False)
    op.create_table('content_performance',
    sa.Column('performance_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('spotify_traffic_lift', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['content_posts.post_id'], ),
    sa.PrimaryKeyConstraint('performance_id')
    )
    op.create_index(op.f('ix_content_performance_artist_id'), 'content_performance', ['artist_id'], unique=False)
    op.create_index(op.f('ix_content_performance_post_id'), 'content_performance', ['post_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['content_posts.post_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_predictions_artist_id'), 'predictions', ['artist_id'], unique=False)
    op.create_index(op.f('ix_predictions_post_id'), 'predictions', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_post_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_artist_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_content_performance_post_id'), table_name='content_performance')
    op.drop_index(op.f('ix_content_performance_artist_id'), table_name='content_performance')
    op.drop_table('content_performance')
    op.drop_index(op.f('ix_platform_connections_artist_id'), table_name='platform_connections')
    op.drop_index('idx_platform_connections_artist_platform', table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_experiments_artist_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_daily_metrics_artist_id'), table_name='daily_metrics')
    op.drop_index('idx_daily_metrics_artist_date', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_content_posts_artist_id'), table_name='content_posts')
    op.drop_index('idx_content_posts_artist', table_name='content_posts')
    op.drop_table('content_posts')
    op.drop_index(op.f('ix_artists_user_id'), table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

